from pathlib import Path


def main() -> int:
    out = Path(__file__).with_name("deployment_guide.txt")
    out.write_text("Deployment guide placeholder generated by script.\n", encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
